const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Plugins.Text,
		C3.Behaviors.bound,
		C3.Behaviors.Flash,
		C3.Behaviors.Platform,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetCeilingCollision,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.scrollto.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Platform.Acts.SetDoubleJumpEnabled,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Behaviors.Platform.Acts.ResetDoubleJump,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Touch.Cnds.OnTapGesture
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{chaobf: 0},
	{Teclado: 0},
	{Mouse: 0},
	{CentrarEm: 0},
	{camera: 0},
	{Texto: 0},
	{Nome_Jogo: 0},
	{BotaoPaly: 0},
	{Fundo_01: 0},
	{Fundo_02: 0},
	{Fundo_Inicio: 0},
	{Lado: 0},
	{Vida: 0},
	{RestritoAoLayout: 0},
	{Piscar: 0},
	{Plataforma: 0},
	{Capivara: 0},
	{Fogo_Boitata: 0},
	{Colisao_Luta: 0},
	{Senóide: 0},
	{Tronco: 0},
	{Troco_pe: 0},
	{dir: 0},
	{Capangas: 0},
	{Baladeira: 0},
	{Arbusto: 0},
	{Áudio: 0},
	{Blocom: 0},
	{Vida_Boitata: 0},
	{Boitata: 0},
	{Boitata_S: 0},
	{Pedra: 0},
	{N_Pedras: 0},
	{Bandeira_Brasil: 0},
	{Bandeira_EUA: 0},
	{Bandeira_España: 0},
	{Idioma: 0},
	{Reniciar: 0},
	{Caixa_dialogo: 0},
	{Fundo_para: 0},
	{Capivara_D: 0},
	{Texto_Dialogo00: 0},
	{Boitata_D: 0},
	{Texto_Dialogo01: 0},
	{Texto_Dialogo02: 0},
	{BarraVida: 0},
	{Projétil: 0},
	{Pedra_M: 0},
	{Texto_DialogoF00: 0},
	{Fogo_Chao: 0},
	{Bloco_Final: 0},
	{Texto_Creditos: 0},
	{Seta_E: 0},
	{Seta_D: 0},
	{Seta_C: 0},
	{Toque: 0},
	{Botao_A: 0},
	{Sobre: 0},
	{Seta_Voltar: 0},
	{Placa_Cap: 0},
	{Sobre_cap: 0},
	{Sobre_boitata: 0},
	{Placa_Boitata: 0},
	{Placa: 0},
	{Sobre_cap2: 0},
	{Sobre_boitata2: 0},
	{Tacacá: 0},
	{Baladeira2: 0},
	{Tacacá2: 0},
	{N_tacaca: 0},
	{N_baladeira: 0},
	{Carregar: 0},
	{Texto_O00: 0},
	{Texto_O1: 0},
	{tacaca: 0},
	{Tacacá3: 0},
	{Tacacá4: 0},
	{espaco: 0},
	{Baladeira3: 0},
	{baladeita_t: 0},
	{N_tacaca2: 0},
	{Texto_DialogoF1: 0},
	{unama: 0},
	{Carregar2: 0},
	{espaco2: 0},
	{Seta_Voltar2: 0},
	{botao_t: 0},
	{tacaca_co: 0},
	{tacaca_co2: 0},
	{Vida_Capivara: 0},
	{DialogoFinal: 0},
	{DialogoDerrota: 0},
	{LutaBoitata: 0},
	{Pegar_tacaca: 0},
	{N_tacacab: 0}
];

self.InstanceType = {
	chaobf: class extends self.ITiledBackgroundInstance {},
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	camera: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Nome_Jogo: class extends self.ISpriteInstance {},
	BotaoPaly: class extends self.ISpriteInstance {},
	Fundo_01: class extends self.ISpriteInstance {},
	Fundo_02: class extends self.ISpriteInstance {},
	Fundo_Inicio: class extends self.ISpriteInstance {},
	Capivara: class extends self.ISpriteInstance {},
	Fogo_Boitata: class extends self.ISpriteInstance {},
	Colisao_Luta: class extends self.ISpriteInstance {},
	Tronco: class extends self.ISpriteInstance {},
	Troco_pe: class extends self.ISpriteInstance {},
	Capangas: class extends self.ISpriteInstance {},
	Baladeira: class extends self.ISpriteInstance {},
	Arbusto: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Blocom: class extends self.ISpriteInstance {},
	Boitata: class extends self.ISpriteInstance {},
	Boitata_S: class extends self.ISpriteInstance {},
	Pedra: class extends self.ISpriteInstance {},
	N_Pedras: class extends self.ITextInstance {},
	Bandeira_Brasil: class extends self.ISpriteInstance {},
	Bandeira_EUA: class extends self.ISpriteInstance {},
	Bandeira_España: class extends self.ISpriteInstance {},
	Idioma: class extends self.ITextInstance {},
	Reniciar: class extends self.ISpriteInstance {},
	Caixa_dialogo: class extends self.ISpriteInstance {},
	Fundo_para: class extends self.ISpriteInstance {},
	Capivara_D: class extends self.ISpriteInstance {},
	Texto_Dialogo00: class extends self.ITextInstance {},
	Boitata_D: class extends self.ISpriteInstance {},
	Texto_Dialogo01: class extends self.ITextInstance {},
	Texto_Dialogo02: class extends self.ITextInstance {},
	BarraVida: class extends self.ISpriteInstance {},
	Pedra_M: class extends self.ISpriteInstance {},
	Texto_DialogoF00: class extends self.ITextInstance {},
	Fogo_Chao: class extends self.ISpriteInstance {},
	Bloco_Final: class extends self.ISpriteInstance {},
	Texto_Creditos: class extends self.ITextInstance {},
	Seta_E: class extends self.ISpriteInstance {},
	Seta_D: class extends self.ISpriteInstance {},
	Seta_C: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	Botao_A: class extends self.ISpriteInstance {},
	Sobre: class extends self.ISpriteInstance {},
	Seta_Voltar: class extends self.ISpriteInstance {},
	Placa_Cap: class extends self.ISpriteInstance {},
	Sobre_cap: class extends self.ITextInstance {},
	Sobre_boitata: class extends self.ITextInstance {},
	Placa_Boitata: class extends self.ISpriteInstance {},
	Placa: class extends self.ISpriteInstance {},
	Sobre_cap2: class extends self.ITextInstance {},
	Sobre_boitata2: class extends self.ITextInstance {},
	Tacacá: class extends self.ISpriteInstance {},
	Baladeira2: class extends self.ISpriteInstance {},
	Tacacá2: class extends self.ISpriteInstance {},
	N_tacaca: class extends self.ITextInstance {},
	N_baladeira: class extends self.ITextInstance {},
	Carregar: class extends self.ISpriteInstance {},
	Texto_O00: class extends self.ITextInstance {},
	Texto_O1: class extends self.ITextInstance {},
	tacaca: class extends self.ITextInstance {},
	Tacacá3: class extends self.ISpriteInstance {},
	Tacacá4: class extends self.ISpriteInstance {},
	espaco: class extends self.ITextInstance {},
	Baladeira3: class extends self.ISpriteInstance {},
	baladeita_t: class extends self.ITextInstance {},
	N_tacaca2: class extends self.ITextInstance {},
	Texto_DialogoF1: class extends self.ITextInstance {},
	unama: class extends self.ISpriteInstance {},
	Carregar2: class extends self.ISpriteInstance {},
	espaco2: class extends self.ITextInstance {},
	Seta_Voltar2: class extends self.ISpriteInstance {},
	botao_t: class extends self.ISpriteInstance {}
}